project/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^index', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^about', views.AboutView.as_view(), name='about'),
    url(r'^contact', views.ContactView.as_view(), name='contact'),
]

project/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss')
]

project/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>\d+)/$', views.post_comment, name='post_comment'),
]

project/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=24, verbose_name='分类')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=24, verbose_name='标签')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=32, verbose_name='博文')
    excerpt = models.CharField(max_length=124, blank=True, verbose_name='概要')
    source_url = models.URLField(verbose_name='引文地址', null=True, blank=True, help_text='options')
    content = models.TextField(verbose_name='内容')
    created_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    modified_time = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    category = models.ForeignKey(Category, verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')
    author = models.ForeignKey(User, verbose_name='作者', default=1)
    view_times = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.view_times += 1
        self.save(update_fields=['view_times'])

    def save(self, *args, **kwargs):
        self.excerpt = self.content[:108]
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time', 'view_times']

project/comments/models.py
from django.db import models


class Comment(models.Model):
    name = models.CharField(max_length=16, default='anonymous')
    email = models.EmailField(max_length=32)
    url = models.URLField(blank=True, null=True, help_text='options')
    text = models.TextField(max_length=1024, help_text='评论内容...', verbose_name='评论')
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

    class Meta:
        ordering = ['-created_time']

project/blog/views.py
import markdown
from django.shortcuts import get_object_or_404
from .models import Post, Category, Tag
from comments.forms import CommentForm
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.views.generic import ListView, DetailView
import logging

log = logging.getLogger(__name__)


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        log.info('the web got a page view...')
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 6

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


class ArchivesView(IndexView):
    def get_queryset(self):
        return super(ArchivesView, self).get_queryset().filter(
            created_time__year=self.kwargs.get('year'),
            created_time__month=self.kwargs.get('month'))


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.content = md.convert(post.content)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update(
            {'form': form,
             'comment_list': comment_list
             }
        )
        return context


class AboutView(ListView):
    model = Post
    template_name = 'blog/about.html'


class ContactView(ListView):
    model = Post
    template_name = 'blog/contact.html'

project/templates/blog/about.html
<!DOCTYPE html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
    <title>
        Losing such an important research tool would significantly compromise scientists efficiency - TimWells
    </title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <style> span.highlighted {
        color: red;
    }</style>
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body id="page">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b style="font-size: 1em">*T*</b> - timwells</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <!--<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>-->
                            <!--<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>-->
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <!--<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>-->
                            <li class="cl-effect-11"><a href="http://127.0.0.1:8000/admin"><span
                                    class="icon ion-pin"></span></a></li>
                            <li class="cl-effect-11">
                                <div id="header-search-box">
                                    <div id="search-form" class="search-form">
                                        <form role="search" method="get" id="searchform"
                                              action="{% url 'haystack_search' %}">
                                            {% csrf_token %}
                                            <input type="search" name="q" placeholder="搜索" required>
                                            <button type="submit"><span class="ion-ios-search-strong"></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <h1 class="page-title">About Me</h1>
                <article class="post">
                    <div class="entry-content clearfix">
                        <figure class="img-responsive-center">
                            <img class="img-responsive" src="{% static 'blog/img/me.jpg' %}" alt="me.jpg">
                        </figure>
                        <p>Born in 1987, and graduate at 2009 from University of HeNan Institute of Science and
                            Technology.Work on International Foreign Trade Since 2009 to 2013, and after that start his
                            venture in all kind of business, doing some trade in 2013-2014, 'surfing' on Internet...
                            till now, and looks to be last forever!</p>
                        <p>2017-2017 Technical: Python: Web Crawling, Flask/Django, Data(ing)...; Base: Html/css/js,
                            Docker, linux...</p>
                        <div class="height-40px"></div>
                        <h2 class="title text-center">Social</h2>
                        <ul class="social">
                            <li class="facebook"><a href="#"><span title="1807520300@qq.com">@Email</span></a></li>
                            <li class="twitter"><a href="#"><span title="TimWells">WeChat</span></a></li>
                            <!--<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>-->
                            <!--<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>-->
                        </ul>
                    </div>
                </article>
            </main>
        </div>
    </div>
</div>

<!--footer-->
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 基于<a target="_blank" title="python django">Python django</a>
                    - 由<a href="#" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <!--<li><a href="full-width.html">博客</a></li>-->
            <li><a href="about.html">关于</a></li>
            <li class="cl-effect-11"><a href="{% url 'admin:index' %}"><span
                    class="icon ion-pin"></span></a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

project/templates/blog/contact.html
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body id="page">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="Search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <h1 class="page-title">Contact</h1>
                <article class="post">
                    <div class="entry-content clearfix">
                        <form action="#" method="post" class="contact-form">
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    <input type="text" name="name" placeholder="Name" required>
                                    <input type="email" name="email" placeholder="Email" required>
                                    <input type="text" name="subject" placeholder="Subject" required>
                                    <textarea name="message" rows="7" placeholder="Your Message" required></textarea>
                                    <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span>
                                    </button>
                                </div>
                            </div>    <!-- row -->
                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy; 2014 ThemeWagon.com</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="full-width.html">Blog</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>

project/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
            <span class="post-date">
                    <a href="#">
                        <time class="entry-date" datetime="{{ post.created_time }}">
                            {{ post.created_time }}
                        </time>
                    </a>
                </span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.view_times }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.content|safe }}
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            </li>
            {% empty %}
            暂无评论
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}
{% block toc %}
<aside>
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
</aside>
<!--<div class="widget widget-tag-cloud">-->
<!--<h3 class="widget-title">标签云</h3>-->
<!--<ul>-->
<!--</ul>-->
<!--</div>-->
{% endblock toc %}

project/templates/blog/full-width.html
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/ionicons.min.css">
    <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css">

    <!-- js -->
    <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="Search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Web Design</a></span>

                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

                            <span class="post-author"><a href="#">Albert Einstein</a></span>

                            <span class="comments-link"><a href="">4 Comments</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and
                            flow of things. There are many variations of passages of Lorem Ipsum available, but the
                            majority have suffered alteration in some form, by injected humour, or randomised words
                            which don’t look even slightly.</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>

                <article class="post post-2">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">Web Design</a></span>

                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

                            <span class="post-author"><a href="#">Albert Einstein</a></span>

                            <span class="comments-link"><a href="#">4 Comments</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and
                            flow of things. There are many variations of passages of Lorem Ipsum available, but the
                            majority have suffered alteration in some form, by injected humour, or randomised words
                            which don’t look even slightly.</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>

                <article class="post post-3">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#" rel="category tag">Web Design</a></span>

                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

                            <span class="post-author"><a href="#">Albert Einstein</a></span>

                            <span class="comments-link"><a href="#">4 Comments</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and
                            flow of things. There are many variations of passages of Lorem Ipsum available, but the
                            majority have suffered alteration in some form, by injected humour, or randomised words
                            which don’t look even slightly.</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>

                <article class="post post-4">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="single.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#" rel="category tag">Web Design</a></span>

                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>

                            <span class="post-author"><a href="#">Albert Einstein</a></span>

                            <span class="comments-link"><a href="#">4 Comments</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and
                            flow of things. There are many variations of passages of Lorem Ipsum available, but the
                            majority have suffered alteration in some form, by injected humour, or randomised words
                            which don’t look even slightly.</p>
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
            </main>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy; 2014 ThemeWagon.com</p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="full-width.html">Blog</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</html>